#include <stdio.h>
#include <math.h>
#include <string.h>
int CalculateChinese();
int BrochureChinese();
void PrintScreenChinese();
void TriangleChinese();
void StatisticChinese();
void Integral();
void Derivative();
void Calculate();
